from openai import OpenAI
from os import getenv
from autogen import *
from pyexpat.errors import messages

llm_config = {
    "config_list": [{
        "model": "gpt-3.5-turbo",
        "base_url": "https://chatapi.littlewheat.com/v1",
        "api_key": "sk-jyutGKHl4dXtVKfXiKLy8u1mLimomF8of4Oc4VPOE5kYhBZk"
    }]
}

agent_kt = ConversableAgent(  # 知识追踪代理
    name="agent_kt",
    llm_config=llm_config,
    system_message="You are a knowledge tracking expert; "
                   "you will receive a list containing question information and students' answer statuses. "
                   "Your task is to summarize the student's mastery of all knowledge points from this list.",
)

agent_exeGen_generator = ConversableAgent(  # 习题生成代理
    name="agent_exeGen_generator",
    llm_config=llm_config,
    system_message="You are an exercise generation expert; "
                   "you will receive a list containing question information and students' answer statuses, as well as the knowledge tracking expert's summary of the student's mastery of the knowledge points. "
                   "Based on this information, you need to generate new questions and their answers for students to practice.",
)

# 5个习题评判专家
agent_exeGen_discriminator_1 = ConversableAgent(
    name="agent_exeGen_discriminator_1",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing question information and students' answer statuses, the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new questions generated by the exercise generation expert, and their answers. "
                   "You need to judge whether the newly generated exercises are reasonable based on this information.",
)

agent_exeGen_discriminator_2 = ConversableAgent(
    name="agent_exeGen_discriminator_2",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing question information and students' answer statuses, the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new questions generated by the exercise generation expert, and their answers. "
                   "You need to judge whether the newly generated exercises are reasonable based on this information.",
)

agent_exeGen_discriminator_3 = ConversableAgent(
    name="agent_exeGen_discriminator_3",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing question information and students' answer statuses, the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new questions generated by the exercise generation expert, and their answers. "
                   "You need to judge whether the newly generated exercises are reasonable based on this information.",
)

agent_exeGen_discriminator_4 = ConversableAgent(
    name="agent_exeGen_discriminator_4",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing question information and students' answer statuses, the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new questions generated by the exercise generation expert, and their answers. "
                   "You need to judge whether the newly generated exercises are reasonable based on this information.",
)

agent_exeGen_discriminator_5 = ConversableAgent(
    name="agent_exeGen_discriminator_5",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing question information and students' answer statuses, the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new questions generated by the exercise generation expert, and their answers. "
                   "You need to judge whether the newly generated exercises are reasonable based on this information.",
)

agent_host = ConversableAgent(
    name="agent_host",
    llm_config=llm_config,
    system_message="You are the moderator of this meeting; "
                   "first, you will obtain a list containing question information and students' answer statuses. You need to pass this list to agent_kt to generate a knowledge state. "
                   "Then, you need to have agent_exeGen_generator create new questions. "
                   "Finally, you need to submit the newly generated questions to all agent_exeGen_discriminators for evaluation. "
                   "If they deem the exercises unsatisfactory, you will need to go back to the previous step and have agent_exeGen_generator generate the questions again.",
)
