# json和自然语言两种提示词格式
# 采样实验数据 1000个用户
# example库添加语意向量属性,使用bert生成,计算向量相似度匹配example 取前三
# 生成题型统一为四种,每次生成只生成同一种题型
# 代理不读取多余信息
# 添加一个判断答案是否正确的代理
# 链接内容
# 不用限定新知识点数量
# 统一用词为exercise
# 输出格式改为参数,可选格式
# 生成example表中的所有解释
# 思维链
# 生成数量
# 每个知识点匹配正负example
# 硬匹配和软匹配
# todo: 做实验

from openai import OpenAI
from os import getenv
from autogen import *
from pyexpat.errors import messages
from create_prompt import *
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--type_of_prompt", type=str, help="natural_language_text or json_text")
parser.add_argument("--exercise_type", type=str,
                    help="Single_Choice or Multiple_Choice or True or False or Short Answer")
parser.add_argument("--output_type", type=str, help="natural_language or json")
parser.add_argument("--Number_of_Generations", type=int)

stuRec_1000_with_tokens = pandas.read_csv("subject_data(1)/stuRec_1000_with_tokens.csv")
examples_with_explanation_with_tokens = pandas.read_csv("subject_data(1)/examples_with_explanation_with_tokens.csv")
concept_relation_filtered = pandas.read_csv("subject_data(1)/concept_relationship_filtered.csv")

llm_config = {
    "config_list": [{
        "model": "openai/gpt-4o",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key": "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",
        "price": [0.5, 1.5]
    }]
}

examplar_gene = ConversableAgent(
    name='examplar',
    llm_config=llm_config,
    system_message="",
)

agent_kt = ConversableAgent(  # 知识追踪代理
    name="agent_kt",
    llm_config=llm_config,
    system_message="You are a knowledge tracking expert;"
                   "You will receive a file containing some sample exercises and the student's record of doing the exercises, where the explanation attribute represents the reason why the student got the exercises right or wrong"
                   "Your task is to complete the explanation attribute of the task list and return the complete list and summarize the student's mastery of all the knowledge points in the list. Let's think step by step"
                   "Don't send any goodbyes when the task is complete",
)

exercise_type = parser.parse_args().exercise_type
exercise_number = parser.parse_args().Number_of_Generations

agent_exeGen_generator = ConversableAgent(  # 习题生成代理
    name="agent_exeGen_generator",
    llm_config=llm_config,
    system_message="You are an exercise generation expert; "
                   "you will receive a list containing the knowledge tracking expert's summary of the student's mastery of the knowledge points. "
                   f"Based on this information, you will need to generate {exercise_number} new {exercise_type} exercises and their answers in the format provided, indicating the knowledge points they contain for students to practice."
                   "Don't send any goodbyes when the task is complete",
)

# 3个习题评判专家
agent_exeGen_discriminator_1 = ConversableAgent(
    name="agent_exeGen_discriminator_1",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list the new exercises and their answers generated by the exercise generation expert. "
                   "You will need to determine if the newly generated exercises are linguistically fluent based on this information."
                   "Don't send any goodbyes when the task is complete",
)

agent_exeGen_discriminator_2 = ConversableAgent(
    name="agent_exeGen_discriminator_2",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new exercises and their answers generated by the exercise generation expert. "
                   "You need to use this information to determine whether the newly generated exercises cover the required knowledge points."
                   "Don't send any goodbyes when the task is complete",
)

agent_exeGen_discriminator_3 = ConversableAgent(
    name="agent_exeGen_discriminator_3",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing the new exercises generated by the exercise generation expert, and their answers. "
                   "You need to use this information to determine if the newly generated exercises are correct and reasonable."
                   "Don't send any goodbyes when the task is complete",
)

formet = parser.parse_args().output_type
if formet == "natural_language_text":
    f = open("txtfile/n_output.txt", "r")
    o_fmt = f.read()
elif formet == "json_text":
    f = open("txtfile/j_output.txt", "r")
    o_fmt = f.read()

agent_exe = ConversableAgent(
    name="agent_exe",
    llm_config=llm_config,
    system_message=f"After all agent_exeGen_discriminators agree that the generated list of exercises is correct, you need to send the final version of the list of exercises once more in {formet} format and terminate the chat",
)

out_groupchat = GroupChat(
    agents=[agent_kt, agent_exeGen_generator, agent_exeGen_discriminator_1, agent_exeGen_discriminator_2,
            agent_exeGen_discriminator_3, agent_exe],
    messages=[],
    send_introductions=True,
)

out_groupchat_manager = GroupChatManager(
    groupchat=out_groupchat,
    llm_config=llm_config,
)

text = {
    "examples": [],
    "tasks": []
}

# 获取task数组
stuRec_1000_with_tokens = stuRec_1000_with_tokens.head(10)
selected_columns1 = ['content', 'option', 'right_answer', 'course_name', 'concept_id', 'is_correct', 'explanation',
                     'knowledge_chain']

# 硬匹配
hard_example, stuRec_1000_with_tokens = get_examples_by_concept(examples_with_explanation_with_tokens,
                                                                stuRec_1000_with_tokens)
hard_example = hard_example[selected_columns1]

text['examples'] += hard_example.to_dict(orient='records')

# 软匹配
if not stuRec_1000_with_tokens.empty:
    res = get_examples_by_similarity(examples_with_explanation_with_tokens, stuRec_1000_with_tokens)[
        selected_columns1].to_dict(orient='records')

    text["examples"] += res

# 匹配完成后重新读取习题记录信息
stuRec_1000_with_tokens = pandas.read_csv("subject_data(1)/stuRec_1000_with_tokens.csv")
stuRec_1000_with_tokens = stuRec_1000_with_tokens.head(10)
selected_columns2 = ['content', 'option', 'right_answer', 'course_name', 'concept_id', 'is_correct']
stuRec_1000_with_tokens = stuRec_1000_with_tokens[selected_columns2]

# 计算习题记录的知识链
stuRec_1000_with_tokens["knowledge_chain"] = ""
for index, row in stuRec_1000_with_tokens.iterrows():
    chain = get_chain(row['concept_id'], row['concept_id'])
    stuRec_1000_with_tokens.at[index, 'knowledge_chain'] = chain

stuRec_1000_with_tokens["explanation"] = ""
stuRec_1000_with_tokens = stuRec_1000_with_tokens.to_dict(orient='records')
text["tasks"] = stuRec_1000_with_tokens

text = json.dumps(text, ensure_ascii=False, indent=4)

# 将提示词文本转换为自然语言形式
n_text = json.loads(text)


def convert_to_natural_language(text):
    natural_language_text = ""

    # 处理examples
    natural_language_text += "examples:\n"
    flag = 0
    for example in text['examples']:
        content = example['content']
        options = example['option']
        right_answer = example['right_answer']
        is_correct = example['is_correct']
        concept_id = example['concept_id']
        course_name = example['course_name']
        knowledge_chain = example['knowledge_chain']
        explanation = example['explanation']

        flag += 1
        natural_language_text += str(flag) + ",\n"

        natural_language_text += "content:" + content + "\n"
        natural_language_text += "option:" + options + "\n"
        natural_language_text += "right_answer:" + right_answer + "\n"
        natural_language_text += "is_correct:" + str(is_correct) + "\n"
        natural_language_text += "concept_id:" + concept_id + "\n"
        natural_language_text += "course_name:" + course_name + "\n"
        natural_language_text += "knowledge_chain:" + knowledge_chain + "\n"
        natural_language_text += "explanation:" + explanation + "\n"

    # 处理tasks，逻辑与examples相同
    natural_language_text += "tasks:\n"
    flag = 0
    for task in text['tasks']:
        content = task['content']
        options = task['option']
        right_answer = task['right_answer']
        is_correct = task['is_correct']
        concept_id = task['concept_id']
        course_name = task['course_name']
        knowledge_chain = task['knowledge_chain']
        explanation = task['explanation']

        flag += 1
        natural_language_text += str(flag) + ",\n"
        natural_language_text += "content:" + content + "\n"
        natural_language_text += "option:" + options + "\n"
        natural_language_text += "right_answer:" + right_answer + "\n"
        natural_language_text += "is_correct:" + str(is_correct) + "\n"
        natural_language_text += "concept_id:" + concept_id + "\n"
        natural_language_text += "course_name:" + course_name + "\n"
        natural_language_text += "knowledge_chain:" + knowledge_chain + "\n"
        natural_language_text += "explanation:" + explanation + "\n"

    return natural_language_text


n_text = convert_to_natural_language(n_text)

agent_kt.description = "a knowledge tracking expert"
agent_exeGen_generator.description = "an exercise generation expert"
agent_exeGen_discriminator_1.description = "exercise evaluation expert 1"
agent_exeGen_discriminator_2.description = "exercise evaluation expert 2"
agent_exeGen_discriminator_3.description = "exercise evaluation expert 3"

type = parser.parse_args().type_of_prompt
if type == "natural_language_text":
    prompt = n_text
elif type == "json_text":
    prompt = text

chat_res = out_groupchat_manager.initiate_chat(
    out_groupchat_manager,
    message="You are the moderator of this meeting; "
            "first, you will obtain a list containing exercises information and a given student's answer statuses. You need to pass this list to agent_kt to generate a knowledge state. "
            "Then, you need to have agent_exeGen_generator create ten new exercises. "
            "Finally, you need to submit the newly generated exercises to all agent_exeGen_discriminators for evaluation, with each agent_exeGen_discriminator being responsible for a different aspect of the correctness review"
            "If any of the agent_exeGen_discriminators find these exercises unsatisfactory, you need to go back to the previous step and have agent_exeGen_generator regenerate the problem."
            "After all agent_exeGen_discriminators have agreed that the list of exercises generated is correct, you need to let agent_exe speak to terminate the chat\n" + prompt,
    summary_method="reflection_with_llm",
)

# json_pattern = r'\{[^{}]*\}'
# matches = re.findall(json_pattern, chat_res, re.DOTALL)
#
# # 获取最后一个匹配的JSON字符串
# last_json_str = matches[-1] if matches else None
#
# # 将JSON字符串解析为Python字典
# if last_json_str:
#     last_json_obj = json.loads(last_json_str)
#     print(last_json_obj)
# else:
#     print("没有找到JSON对象")
