from openai import OpenAI
from os import getenv
from autogen import *
from pyexpat.errors import messages
from create_prompt import *
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--type_of_prompt", type=str, help="natural_language_text or json_text")
parser.add_argument("--exercise_type", type=str,
                    help="Single_Choice or Multiple_Choice or True or False or Short Answer")
parser.add_argument("--output_type", type=str, help="natural_language_text or json_text")

llm_config = {
    "config_list": [{
        "model": "openai/gpt-4o",
        "base_url": "https://openrouter.ai/api/v1",
        "api_key": "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",
        "price": [0.5, 1.5]
    }]
}

examplar_gene = ConversableAgent(
    name='examplar',
    llm_config=llm_config,
    system_message="",
)

# json和自然语言两种提示词格式
# 采样实验数据 1000个用户
# example库添加语意向量属性,使用bert生成,计算向量相似度匹配example 取前三
# 生成题型统一为四种,每次生成只生成同一种题型
# 代理不读取多余信息
# 添加一个判断答案是否正确的代理
# 链接内容
# 不用限定新知识点数量
# 统一用词为exercise
# 输出格式改为参数,可选格式
# 生成example表中的所有解释
# todo: 思维链
# todo: 生成数量
# todo: 每个知识点匹配正负example
# todo: 硬匹配和软匹配
# todo: 做实验

agent_kt = ConversableAgent(  # 知识追踪代理
    name="agent_kt",
    llm_config=llm_config,
    system_message="You are a knowledge tracking expert;"
                   "You will receive a file containing some sample exercises and the student's record of doing the exercises, where the explanation attribute represents the reason why the student got the exercises right or wrong"
                   "Your task is to complete the explanation attribute of the task list and return the complete list and summarize the student's mastery of all the knowledge points in the list.",
)

exercise_type = parser.parse_args().exercise_type

agent_exeGen_generator = ConversableAgent(  # 习题生成代理
    name="agent_exeGen_generator",
    llm_config=llm_config,
    system_message="You are an exercise generation expert; "
                   "you will receive a list containing the knowledge tracking expert's summary of the student's mastery of the knowledge points. "
                   f"Based on this information, you will need to generate ten new {exercise_type} exercises and their answers in the format provided, indicating the knowledge points they contain for students to practice.",
)

# 3个习题评判专家
agent_exeGen_discriminator_1 = ConversableAgent(
    name="agent_exeGen_discriminator_1",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list the new exercises and their answers generated by the exercise generation expert. "
                   "You will need to determine if the newly generated exercises are linguistically fluent based on this information.",
)

agent_exeGen_discriminator_2 = ConversableAgent(
    name="agent_exeGen_discriminator_2",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new exercises and their answers generated by the exercise generation expert. "
                   "You need to use this information to determine whether the newly generated exercises cover the required knowledge points.",
)

agent_exeGen_discriminator_3 = ConversableAgent(  # 暂时不使用
    name="agent_exeGen_discriminator_3",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing the knowledge tracking expert's summary of the student's mastery of the knowledge points, the new exercises and their answers generated by the exercise generation expert. "
                   "You need to use this information to determine if the newly generated exercise contains new knowledge points.",
)

agent_exeGen_discriminator_4 = ConversableAgent(
    name="agent_exeGen_discriminator_4",
    llm_config=llm_config,
    system_message="You are an exercise evaluation expert; "
                   "you will receive a list containing the new exercises generated by the exercise generation expert, and their answers. "
                   "You need to use this information to determine if the newly generated exercises are correct and reasonable.",
)

formet = parser.parse_args().output_type
if formet == "natural_language_text":
    f = open("txtfile/n_output.txt", "r")
    o_fmt = f.read()
elif formet == "json_text":
    f = open("txtfile/j_output.txt", "r")
    o_fmt = f.read()

agent_host = ConversableAgent(
    name="agent_host",
    llm_config=llm_config,
    system_message="You are the moderator of this meeting; "
                   "first, you will obtain a list containing exercises information and a given student's answer statuses. You need to pass this list to agent_kt to generate a knowledge state. "
                   "Then, you need to have agent_exeGen_generator create ten new exercises. "
                   "Finally, you need to submit the newly generated exercises to all agent_exeGen_discriminators for evaluation, with each agent_exeGen_discriminator being responsible for a different aspect of the correctness review"
                   "If any of the agent_exeGen_discriminators find these exercises unsatisfactory, you need to go back to the previous step and have agent_exeGen_generator regenerate the problem."
                   "Finally, after all agent_exeGen_discriminators agree that the generated list of exercises is correct, the final version of the list of exercises needs to be returned in the following format, and then let the dialog end" + o_fmt,
)

agent_kt.description = "a knowledge tracking expert"
agent_exeGen_generator.description = "an exercise generation expert"
agent_exeGen_discriminator_1.description = "exercise evaluation expert 1"
agent_exeGen_discriminator_2.description = "exercise evaluation expert 2"
agent_exeGen_discriminator_3.description = "exercise evaluation expert 3"
agent_exeGen_discriminator_4.description = "exercise evaluation expert 4"
agent_host.description = "the host of this meeting"

out_groupchat = GroupChat(
    agents=[agent_kt, agent_exeGen_generator, agent_exeGen_discriminator_1, agent_exeGen_discriminator_2,
            agent_exeGen_discriminator_4, agent_host],
    messages=[],
    send_introductions=True,
)

out_groupchat_manager = GroupChatManager(
    groupchat=out_groupchat,
    llm_config=llm_config,
)

type = parser.parse_args().type_of_prompt
if type == "natural_language_text":
    prompt = n_text
elif type == "json_text":
    prompt = text

chat_res = agent_host.initiate_chat(
    out_groupchat_manager,
    message=prompt,
    summary_method="reflection_with_llm",
)
